schema_version = "0.0.1"
id = "DCM2VDB"
version = "0.0.1"
name = "DICOM to VDB"
tagline = "just tests"
maintainer = "Your Name <you@example.com>"
type = "add-on"
license = ["GPL-3.0-or-later"]

# Blender version compatibility
blender_version_min = "5.0.0"

platforms = ["windows-x64", "macos-arm64","linux-x64"]

# Python wheels (dependencies)
wheels = [
    "./wheels/pydicom-3.0.1-py3-none-any.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/scipy-1.16.3-cp311-cp311-macosx_14_0_arm64.whl",
    "./wheels/scipy-1.16.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/scipy-1.16.3-cp311-cp311-win_amd64.whl",
    # GPU acceleration - MLX for macOS ARM64
    "./wheels/mlx-0.30.3-cp311-cp311-macosx_14_0_arm64.whl",
    "./wheels/mlx_metal-0.30.3-py3-none-macosx_14_0_arm64.whl",
    # GPU acceleration - CuPy for NVIDIA CUDA
    "./wheels/cupy_cuda12x-13.6.0-cp311-cp311-win_amd64.whl",
    "./wheels/cupy_cuda12x-13.6.0-cp311-cp311-manylinux2014_x86_64.whl",
]
