schema_version = "0.0.1"
id = "DCM2VDB"
version = "0.0.1"
name = "DICOM to VDB"
tagline = "just tests"
maintainer = "Your Name <you@example.com>"
type = "add-on"
license = ["GPL-3.0-or-later"]

# Blender version compatibility
blender_version_min = "5.0.0"

# Python wheels (dependencies)
wheels = [
    "./wheels/pydicom-3.0.1-py3-none-any.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl",
]
